platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def pods
  pod 'RIBs', :git => 'https://github.com/uber/RIBs.git', :tag => '0.9.2'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'GoogleUtilities', :modular_headers => true
end

target 'Holder' do
  pods
end

target 'ShareExtension' do
  pods
end
