platform :ios, '13.0'
inhibit_all_warnings!

def pods
  pod 'RIBs', :git => 'https://github.com/uber/RIBs.git', :tag => '0.9.2'
end

target 'Holder' do
  pods
end

target 'ShareExtension' do
  pods
end
